### ISSUE TITLE
[OCLFiddle] Visualization of CD4A (PrintAST)

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/OCL#10]
* use https://www.planttext.com!
* just print a CD4A-AST to a text string (should work with Visitor), so that CheerpJ can run it
* use the the developer console to see how planttext.com sends the text file to the server and how it returns a unique image id to load the image
    * alternatively you can use http://www.plantuml.com/plantuml/uml/

* it works quiet well and should be enough to roughly visualize our classdiagrams for OCL learning purpose

Example:

```
package example.CDs;

classdiagram AuctionCD {
    public class Auction {}
    public class Person {}
    public class Collection {
        int size();
    }
    public class Set extends Collection {}
    public class Boolean {}
    public class Integer {}

    association participants [*] Auction (auctions) <-> (bidder) Person [*];
}
```

must only be translated to:
```
@startuml

title example.CDs.AuctionCD

class Auction
class Person

class Collection {
  +int size()
}

class Set
class Boolean
class Integer

Collection <|-down- Set
Auction "auctions [*]" -up- "bidder [*]" Person: participants

@enduml
```

and this returns than the following better readable result:
![jk-x3i8m3dpz5lod7ae_034ksgkr4ydy28s58gl95bi2yvxtgzqlsexezfsloj59xju1y1l7i4_thqtbtn1v63gnmtsdgesqcsoxincb7abctn2efz6-0n5hli3r5wtmy5rspygp7kdmf1udrwltag7ycum_oei7lzdh3ip2pu3nihamg8qeibxpoozdolpj3kfoodosqyyck94toysv](https://user-images.githubusercontent.com/30497492/34546650-836b9d4e-f0f5-11e7-8ae9-132dfca3cab3.png)

**Comment by vonwenckstern** [comment]
The new layout of OCLFiddle could look like the following:
![version with visualisation](https://user-images.githubusercontent.com/30497492/34546876-45c8690c-f0f7-11e7-81c0-9f0830c561f9.jpg)

**Comment by vonwenckstern** [comment]
@ferdinandmehlan If you have you printed the AST to a textual file with CheerpJ, you can ask @0xJMR  to help you how to integrate the image to the online IDE frame.

@0xJMR if you use the SVG export you can change the SVG styles so that the output will fit better the dark schema (e.g. have no white background and make the black fonts light-gray). Information how to use the server is here: http://plantuml.com/server

**Comment by ferdinandmehlan** [comment]
@0xJMR  @vonwenckstern The last commit on gh-pages now contains the newest version (1.2.0) of the OCLCDTool. When called like this: OCLCDTool -printcd "classdiagramm { class ... }" it should now print a plantuml fitting string.

**Comment by vonwenckstern** [comment]
Hi Ferdinand,

Danke. Du musst einfach nur folgendes machen:
1)	Du schickst den plantUML String an den Server dies geht zum Beispiel wiefolgt:
a.	http://www.plantuml.com/plantuml/proxy?src=https://raw.github.com/plantuml/plantuml-server/master/src/main/webapp/resource/test2diagrams.txt 
wobei der Text jetzt hier in https://raw.githubusercontent.com/plantuml/plantuml-server/master/src/main/webapp/resource/test2diagrams.txt ist
b.	Wenn du gist nutzen möchtest (um anonym, dateien zu speichern, also deinen plantUML Text), dann kannst du wie folgt auf den Inhalt zugreifen:
https://gist.githubusercontent.com/anonymous/9cc79e0fd36389acdd3938ef37bc0aa7/raw/test 
für das angelegte gist: (ich habe es mal selber zum testen anonym angelegt) – du kannst auch gists per JavaScript anlegen
https://gist.github.com/anonymous/9cc79e0fd36389acdd3938ef37bc0aa7#file-test  

Und somit bekommst du dann dein Bild: http://www.plantuml.com/plantuml/proxy?src=https://gist.githubusercontent.com/anonymous/9cc79e0fd36389acdd3938ef37bc0aa7/raw/test 
2)	Der Server gibt dir dann das PNG zurück
3)	Das PNG kannst du dann direkt per img src einbinden

Hier ist noch ein Beispiel wie du ganz einfach per JavaScript den gist erzeugen kannst.

Ich denke mit der Info dürfte es für dich keine Hindernisse mehr geben.

Viele Grüße,
Michael

PS: https://github.com/plantuml/plantuml-server/issues/4 für weitere Infos zum proxy von plantuml

**Comment by vonwenckstern** [comment]
@ferdinandmehlan: Just one remark: Even you can print show the generated file in the browser by calling https://ferdinandmehlan.github.io/OCL/resources/txt/plantUML.txt

you cannot send this location to the proxy server by 
http://www.plantuml.com/plantuml/proxy?src=https://ferdinandmehlan.github.io/OCL/resources/txt/plantUML.txt

The reason for that is that the file is stored locally in the Web-browser cache which only the client can read but not any other server.

For that you need to read the content of https://ferdinandmehlan.github.io/OCL/resources/txt/plantUML.txt in JavaScript and send it to gist, and then you get a link which you can send to the proxy server

**Comment by vonwenckstern** [comment]
@ferdinandmehlan I figured out how it works just as jar without graphviz: http://plantuml.com/smetana02

* `auction.txt`:

```
@startuml
!pragma graphviz_dot jdot
class Foo1

Foo1 --> Foo2
Foo1 --> Foo3
Foo1 ---> Foo4 : test 4
Foo1 ----> Foo5 : test 5

@enduml
```

I run `java -jar plantuml.jar auction.txt` and I got a normal png file.
So it might work with cheerpj.

**Comment by vonwenckstern** [comment]
@https://github.com/EmbeddedMontiArc/OCL/issues/10#issuecomment-368268424 da fehlen aber zurzeit noch die Pfeile (so ist der Server vllt. doch die bessere Lösung).
@ferdinandmehlan ich glaube wir sollten den server nehmen (und ich halte mich ab jetzt da heraus).

**Comment by vonwenckstern** [comment]
Hi @ferdinandmehlan,
ich habe es jetzt eingebaut.
* Allerdings werden die Rollennamen und Assoziationsnamen zurzeit nicht mit ausgegeben.
* Und die Standardassoziationswerte fehlen (also wenn nix da ist, ist es glaube immer eine *-* Assoziation; kannst dafür aber ja mal in den Symboltable-Creator hineinschauen)
* Die Attribute fehlen auch noch also für `class X { Length l; }`

Eventuell könntest du dies ja noch nachholen. Am besten mit folgenden CLI-Optionen: (da hinter dann immer `true` or `false` als Wert)
* `--showAttributes` zeigt auch die Attribute an (default: aus wie jetzt)
* `--showAssociationNames` zeigt auch die Assoziationsnamen an (default: aus wie jetzt)
* `--showRoleNames` zeigt auch die Rollennamen an (default: aus wie jetzt)
* `--showCardinality` zeigt Kardinalitäten (auch die Standardkardinalitäten an) (default: an wie jetzt)

Und dann können wir zwischen den Linken Reload-Button und den Mittleren Run-Button noch `Pushbuttons` (mit Bildern) einfügen um diese Optionen im OCLFiddle zu aktivieren oder Deaktivieren.
https://stackoverflow.com/questions/2738920/how-to-add-background-image-for-input-type-button
Am besten wir nehmen da ein SVG Bild, dann können wir beim Aktivieren einfach die Hintergrundfarbe ändern.

Und es wäre schön, wenn es dann auch noch einen Button (http://iconshow.me/eye-4) gibt auf den man dann klicken kann, damit die Vorschau gerendert wird. Ich denke jetzt kommt keiner auf die Idee auf das Bild zu klicken.

Danke für deine Unterstützung.
Michael

<img width="1280" alt="bildschirmfoto 2018-02-26 um 02 25 25" src="https://user-images.githubusercontent.com/30497492/36649300-5f106666-1a9c-11e8-862c-b207843da141.png">
