### ISSUE TITLE
[OCLFiddle] Replace i logo with names

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/OCL#13]
The popup is nice and looks good.
But the `i logo` looks like information about the tool.
It is better to put there our names (without roles), so that people read it everytime (nobody clicks at the logo). If you click at the names your popup can become visible.

@ferdinandmehlan maybe you want to add a logo of yourself for the popup.

<img width="494" alt="bildschirmfoto 2018-01-05 um 18 51 32" src="https://user-images.githubusercontent.com/30497492/34621714-87cfb0d6-f24a-11e7-80c0-7ad0156e32c9.png">

**Comment by 0xJMR** [comment]
How about a compromise between the two: I will replace it with a label "Creators" or something similar. Or do you really think that it is important that people memorize the name, then I will think about something elegant that still adheres to the above requirements.
The images are actually from GitHub, so if you change your profile avatar, these images will change as well.

**Comment by vonwenckstern** [comment]
Ok, just replace the label with `Development Team`

**Comment by 0xJMR** [comment]
Since there were no new comments on this issue, I assume that the current label satisfies the above requirements. I am closing this issue for now.
