### ISSUE TITLE
[OCLFiddle] OnlineIDE in iframes do not load in Safari

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/OCL#14]
<img width="1280" alt="bildschirmfoto 2018-01-05 um 21 28 07" src="https://user-images.githubusercontent.com/30497492/34627046-629cfb88-f25f-11e7-90e3-cf61b23f33ce.png">

https://drive.google.com/file/d/1f0jS67567wKJgv6ZJFqSWHo_2KlcBj3Z/view?usp=sharing

**Comment by vonwenckstern** [comment]
maybe same issue as https://github.com/EmbeddedMontiArc/onlineIDE/issues/11

but the the online IDE itself loads in Safari:
<img width="1280" alt="bildschirmfoto 2018-01-05 um 21 31 06" src="https://user-images.githubusercontent.com/30497492/34627155-c95d0c96-f25f-11e7-9fdc-87c1ad525256.png">

**Comment by vonwenckstern** [comment]
as we focus mainly on the two browsers: Safari and FireFox it is less important

**Comment by 0xJMR** [comment]
No, I think we should at least try to cover Safari as well. Can you check whether there are any errors in the console? Because this smells of an error caused by browser settings like blocking third party cookies or similar.

**Comment by vonwenckstern** [comment]
This is the console output:

<img width="1278" alt="bildschirmfoto 2018-01-05 um 23 30 02" src="https://user-images.githubusercontent.com/30497492/34631390-6b0d64b8-f270-11e7-878c-f54cf6c7db80.png">

**Comment by 0xJMR** [comment]
Ok, can you click [this link](https://ide.embeddedmontiarc.com/api/load.html?mountPoint=[EmbeddedMontiArc]/OCL/Demos&toggles=1,1,1) and tell me whether it loaded successfully or not?

**Comment by vonwenckstern** [comment]
https://github.com/EmbeddedMontiArc/OCL/issues/14#issuecomment-355684213:
it looks like:
![Uploading Bildschirmfoto 2018-01-05 um 23.37.43.png…]()

**Comment by vonwenckstern** [comment]
If I click at the link of your post, I get the following site:
<img width="1238" alt="bildschirmfoto 2018-01-05 um 23 45 57" src="https://user-images.githubusercontent.com/30497492/34631847-ab8174a6-f272-11e7-8bb1-e19863227116.png">

If I press then the reload button or enter the URL directly in Safari, I get the following site:
<img width="1237" alt="bildschirmfoto 2018-01-05 um 23 47 25" src="https://user-images.githubusercontent.com/30497492/34631881-d4f54024-f272-11e7-9daa-1e4a9467e967.png">

For me it is kind of weired, since once it is shown with workspace and once not. And we do nothing else than redirecting to the webpage or?

**Comment by 0xJMR** [comment]
So if I understood your posts correctly, clicking the link successfully loads the Online IDE. This means that the iframe is what makes the difference. I am still voting for a setting in Safari which blocks access to the Storage API when executed in an iframe (for security purposes).

**Comment by vonwenckstern** [comment]
With the following Developer setting it works:
<img width="1280" alt="bildschirmfoto 2018-01-06 um 00 05 40" src="https://user-images.githubusercontent.com/30497492/34632397-652d806e-f275-11e7-87e7-7b8ea2834f62.png">

**Comment by 0xJMR** [comment]
"Ursprungsübergreifende Beschränkungen" - Cross Origin Restrictions, sounds about right.
It is just a damn shame that Safari does not throw an error which can be caught, so we can actually show a message as to why it does not work, like it is the case in Chrome.

**Comment by vonwenckstern** [comment]
But what I am wondering is that Firefox and Chrome allow it whereas Safari does not allow it.

**Comment by 0xJMR** [comment]
Well, in each browser there is setting which messes with this. In Chrome, for instance, there is an option where a user can disable Third Party Cookies which would render this Fiddle useless. In Firefox, there is a similar option. The difference is that the other two browsers do not enable this option by default.

**Comment by vonwenckstern** [comment]
But this is very Web-Developer unfriendly. If they change the defaults from browser to browser or even from browser version to browser version; things do not work at some point anymore. And nobody knows why.

Maybe we should put a text and links below the `preparing` to say that the Cross-browser Origin must be enabled and the link tells how to enable it.
Or we deploy everything to the same subdomain to avoid such stupid restrictions (this will make our live much easier) - not that also Firefox will change the default in future.

**Comment by vonwenckstern** [comment]
deploying to the same subdomain can be done very easy with Jenkins:
Every time any gh-page will be modified in the specified repos we just copy the content of the gh-pages to a new github-repo project at a very specific location.
And voila everything is then automatically deployed at one subdomain (and we still have the different repos).
Via this deployment we can also rewrite automatically all links in the HTML and JS files so that, you can actually link between the repos as you would do it now, and then we just make a origin-safe deployment.
During this deployment we can also crawl all extern resources such as pictures and so on and copy them too.
Maybe there already exists a tool to do this.

**Comment by vonwenckstern** [comment]
same origin problem could be resolved on gh-pages with submodules: https://stackoverflow.com/questions/33113945/can-jekyll-use-a-config-file-from-a-different-repo

@0xJMR can you read it, and tell me if you think this would solve our problem in an accurate way when combining it with Jeykll `includes` https://jekyllrb.com/docs/includes/?
