### ISSUE TITLE
OCLFiddle is defect

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/OCL#19]
* Ferdinand can you please try to compile the JAR so that it works (I get a class not found exception)
* Jean-Marc, can you invoke the JavaScript parser generated by Ferdinand (after he fixed 1)
    * the new grammar contains many Java-Code and will not parse without it

<img width="1280" alt="bildschirmfoto 2018-02-20 um 00 21 37" src="https://user-images.githubusercontent.com/30497492/36400927-3bdfcdf2-15d4-11e8-9090-80ca4c524207.png">

**Comment by ferdinandmehlan** [comment]
@vonwenckstern should work now

**Comment by vonwenckstern** [comment]
@ferdinandmehlan yes it works now, but now we do not use our local cheerpJ files, so our tool will suddenly crash if cheerpJ makes an update again.

@0xJMR Maybe you can take a look to see if @ferdinandmehlan copied the files at the wrong direction?

**Comment by vonwenckstern** [comment]
Here, I want to thank @0xJMR again; due to his perfect work we can close this issue ;)
