### ISSUE TITLE
Modify main method for OCLCDTool

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/OCL#3]
Hi Ferdinand,

can you please modify the method so that we can also pass the concrete content of the classdiagram and the OCL constraint as parameter.

`java -jar %JAR% - cd "package xyz;\nclassdiagram ABC {\n...\n}" -ocl "package xyz;\nocl {\nconstraint ...\n}"`

Afterwards can you please compile the `ocl-0.0.8-SNAPSHOT-jar-with-dependencies.jar` to JavaScript with the methodology applied in https://github.com/leaningtech/cheerpj-meta/issues/11

And create a simple HTML page where we have two textareas:
* the first one is a class diagramm
* the second one is a OCL constraint

And then pass the content of the textareas as parameter to the generated tool.
See here for instructions:
https://github.com/leaningtech/cheerpj-meta/wiki/Getting-Started#basic-html-page-for-testing

The compiling process throws error, but they should not matter (this is what the developer says).
It also takes quite a long time to compile (about 2 hours) and the size is over 90MB (even the JAR size is under 20MB).

If this would work, we can add a nice HTML page where students can validate their OCL against a classdiagramm.

If you have problems with the tool, you can use the issue below. @alexp-sssup responds very fast.

If it works, please publish the generated JavaScript and the HTML page to github pages.

Thank you,
Michael

**Comment by vonwenckstern** [comment]
you need Python 3.6 (2.7 does not work):
https://www.python.org/downloads/

the link to the bytecode-to-javascript transpiller tool is:
https://leaningtech.com/cheerpj/download/noncommercial/index.html

**Comment by alexp-sssup** [comment]
@vonwenckstern why is this application side change necessary to run on CheerpJ? How does the main method currently work?

**Comment by ferdinandmehlan** [comment]
Right now the main method wants a path to a file with data to process. With the change, the main should take the data directly as string. This is not exactly needed to run CheerpJ, but for the last feature to build an html page in which one can enter data.

**Comment by alexp-sssup** [comment]
CheerpJ supports creating files on the fly from JS using the following command

```
cheerpjAddStringFile("/str/FileName.ext", "fileContentAsJSString")
```

```/str/``` is one of CheerpJ mount points.

**Comment by vonwenckstern** [comment]
@ferdinandmehlan you can also use the method which @alexp-sssup suggested in his comment above.
Then you do not need to modify the tool at all. Then you just copy the textarea content in the file as suggested by alex-ssup.

**Comment by vonwenckstern** [comment]
@0xJMR maybe we can then make it in a way so that our Online-IDE can share there files with CheerpJ (**when the inital test of compiling MontiCores Java-Bytecode to JS works**), then we can integrate there API completely in our toolchain, and have a nice demonstrator page.
We can bridge our VFS with their API (https://github.com/leaningtech/cheerpj-meta/wiki/Runtime-API) to read files and to write files to have a seamless integration of MontiCore and more.

**Comment by ferdinandmehlan** [comment]
@vonwenckstern I've already done the change of the tool, however the proposal of creating files sounds better and more consistent. I'll integrate that later, when the example page works with strings.

@alexp-sssup I've managed to compile the bytecode to js and built a small test page ([https://github.com/EmbeddedMontiArc/OCL/tree/master/OCLCDTool/www]). However I can't see any output and I#m a bit lost on how to achive that.

**Comment by alexp-sssup** [comment]
@ferdinandmehlan Standard output is sent to the browser console unless an HTML element with id "console" is present in the page.

**Comment by vonwenckstern** [comment]
I just moved it to gh-pages, so that it is now accessable via:
https://embeddedmontiarc.github.io/OCL/index.html

**Comment by vonwenckstern** [comment]
<img width="1280" alt="bildschirmfoto 2017-12-02 um 16 13 07" src="https://user-images.githubusercontent.com/30497492/33516979-ca873820-d77b-11e7-88f8-5a7a83c5b210.png">

@ferdinandmehlan the code does not work at my PC (see screenshot, does it work at your PC local?)

**Comment by ferdinandmehlan** [comment]
I dont get th error of class not found. However after that I dont get any further output. I'll try to redo the step of byte -> js because I got some errors there.

![unbenannt](https://user-images.githubusercontent.com/11960127/33517029-caecc22a-d77c-11e7-9a31-03e55837a5b2.PNG)

**Comment by vonwenckstern** [comment]
@alexp-sssup 
we used in https://github.com/EmbeddedMontiArc/OCL/blob/gh-pages/index.html#L25
the full-qualified name such as 
```
cheerpjRunMain("ocl.monticoreocl.ocl.OCLCDTool", "/app/ocl-0.0.8-SNAPSHOT-jar-with-dependencies.jar", "-ocl", oclString, "-cd", cdString);
```

and also the short-name 
```
cheerpjRunMain("OCLCDTool", "/app/ocl-0.0.8-SNAPSHOT-jar-with-dependencies.jar", "-ocl", oclString, "-cd", cdString);
```

but we still get the same errors:
´Error: Could not find or load main class ocl.monticoreocl.ocl.OCLCDTool`

Maybe you can give us a hint what we do wrong invoking `cheerpjRunMain`
Thank you very much.

PS: you can test it at: https://embeddedmontiarc.github.io/OCL/index.html

**Comment by alexp-sssup** [comment]
```/app/``` refers to the root of the server, so you need to use the path ```/app/OCL/ocl-0.0.8-SNAPSHOT-jar-with-dependencies.jar```

**Comment by vonwenckstern** [comment]
@alexp-sssup we changed the path (https://github.com/EmbeddedMontiArc/OCL/blob/gh-pages/index.html#L99), 
but we still get the error
`Error: Could not find or load main class OCLCDTool`

(we tried it both for short-name and full-qualified name)

Do you have any other hints?

**Comment by vonwenckstern** [comment]
it also does not work if I deploy it on my local xampp server (I put everything into the htdocs folder and took as path "/app/ocl-0.0.8-SNAPSHOT-jar-with-dependencies.jar" since the .jar.js directly hosted on the root level of the localhost file)

<img width="1280" alt="bildschirmfoto 2017-12-02 um 17 51 27" src="https://user-images.githubusercontent.com/30497492/33517736-8d2544dc-d789-11e7-8d4e-b5723e88b600.png">
(failed to load it with full-qualified name `cheerpjRunMain("ocl.monticoreocl.ocl.OCLCDTool", "/app/ocl-0.0.8-SNAPSHOT-jar-with-dependencies.jar", "-ocl", oclString, "-cd", cdString);`)


<img width="905" alt="bildschirmfoto 2017-12-02 um 17 55 06" src="https://user-images.githubusercontent.com/30497492/33517758-0a7f3816-d78a-11e7-9f15-7fdec8ba6732.png">
(failed to load with short name `cheerpjRunMain("OCLCDTool", "/app/ocl-0.0.8-SNAPSHOT-jar-with-dependencies.jar", "-ocl", oclString, "-cd", cdString);)

**Comment by alexp-sssup** [comment]
The JAR is expected to be at ```/OCL/ocl-0.0.8-SNAPSHOT-jar-with-dependencies.jar```, but it's not there. You can see from the network tab of the browser developer tools that a 404 error is returned. Are you sure that the JAR is properly deployed on the server? Using the network tab you should be able to debug the issue.

**Comment by vonwenckstern** [comment]
@alexp-sssup but why does your script try to load
https://embeddedmontiarc.github.io/OCL/ocl-0.0.8-SNAPSHOT-jar-with-dependencies.jar
it should load
https://embeddedmontiarc.github.io/OCL/ocl-0.0.8-SNAPSHOT-jar-with-dependencies.jar.js
this file would exist (since it is the js file created by your cmd-tool) and we also **add the .js** ending at the `cheerpjRunMain`

**Comment by vonwenckstern** [comment]
but I will rename the the javascript file right now as bug-fix and see if it works

**Comment by alexp-sssup** [comment]
CheerpJ needs both the original jar and the jar.js files. The JAR is used to provide metadata for reflection, so it can be stripped from all code using the ```--pack-jar``` option of cheerpjfy.py

**Comment by vonwenckstern** [comment]
but we already deployed the jar as you see in
https://github.com/EmbeddedMontiArc/OCL/tree/gh-pages
but github pages will not publish jar-files (I guess it, because the following page is not availalbe:
https://embeddedmontiarc.github.io/OCL/ocl-0.0.8-SNAPSHOT-jar-with-dependencies.jar

@alexp-sssup but with the new option `--pack-jar` we do not need to upload the JAR anymore?

**Comment by alexp-sssup** [comment]
Yes the JAR is always needed, but will be much smaller with --pack-jar

**Comment by vonwenckstern** [comment]
<img width="908" alt="bildschirmfoto 2017-12-02 um 19 18 10" src="https://user-images.githubusercontent.com/30497492/33518466-9bf7b7a4-d795-11e7-85aa-6ff67446b20d.png">
localhost funktioniert jetzt bei mir ;) -- jetzt müssen wir es nur noch auf github-pages zum laufen bekommen
@alexp-sssup können wir auch vorher die jar-Datei irgendwie anders per JavaScript herunterladen und dann in euerem file system ablegen, dass euer Loader dann diese jar-Datei nimmt?

Ich würde sonst nämlich die Datei wiefolgt herunterladen:
https://github.com/EmbeddedMontiArc/OCL/raw/master/OCLCDTool/ocl-0.0.8-SNAPSHOT-jar-with-dependencies.jar

Weil github-pages wohl aus sicherheitsgründen (oder anderen) keine JAR-files deployed :(

**Comment by alexp-sssup** [comment]
(I cannot read german language, I am basing my answer on google translate)

No, it is not possible to download the JAR file in JS and provide it to CheerpJ. The ```/str/``` filesystem only support JS strings at the moment. Moreover it is also not possible to have the JAR at an arbitrary http URL.

You could try to use CheerpJ "split" HTTP mount point. Instead of ```/app/``` use ```/apps/```, then you need to split the JAR files into multiple 1MB chunks and append the ```.cN.txt``` option to them. For example:

```
file.jar -> file.jar.c0.txt, file.jar.c1.txt, etc....
```

If the JAR file is less than 1 MB there will be only 1 chunk: file.jar.c0.txt

**Comment by vonwenckstern** [comment]
sorry that I wrote German.

This with split sounds good.
@ferdinandmehlan Can you please try it out by splitting the jar file and upload it.

**Comment by ferdinandmehlan** [comment]
I'll try that splitting the jar up. 
@alexp-sssup is there a recommedation on how to split them? Else I'd try with an archive manager.
Thank your for your help.

**Comment by alexp-sssup** [comment]
You need to split them at the byte level, on unix system you can use ```split``` or ```dd```, on Windows I don't have any tool to recommend.

**Comment by vonwenckstern** [comment]
It looks good the text files are published to github pages
https://embeddedmontiarc.github.io/OCL/ocl-0.0.8-SNAPSHOT-jar-with-dependencies.jar.c00.txt

**Comment by vonwenckstern** [comment]
@alexp-sssup is it still the same method for the mount split point:
```
heerpjRunMain("ocl.monticoreocl.ocl.OCLCDTool", "/apps/ocl-0.0.8-SNAPSHOT-jar-with-dependencies.jar.c00.txt;/apps/ocl-0.0.8-SNAPSHOT-jar-with-dependencies.jar.c01.txt;/apps/ocl-0.0.8-SNAPSHOT-jar-with-dependencies.jar.c02.txt;...", "-ocl", oclString, "-cd", cdString);
```

I did not find an example (or do we need to call a different function)?

**Comment by vonwenckstern** [comment]
But still github does not serve the one file, I do not know why and hope for a useful answer at stackoverflow:
https://stackoverflow.com/questions/47612211/github-pages-file-is-not-deployed

**Comment by alexp-sssup** [comment]
There are multiple issues here:

1) The file _must_ be called .c0.txt, .c1.txt, etc. c00.txt is _not_ right.
2) Only ```/apps/ocl-0.0.8-SNAPSHOT-jar-with-dependencies.jar``` must be used, CheerpJ will automatically download the chunks as required.

**Comment by vonwenckstern** [comment]
<img width="1280" alt="bildschirmfoto 2017-12-02 um 21 57 21" src="https://user-images.githubusercontent.com/30497492/33519676-e22952da-d7ab-11e7-9155-0caf13ed8b3c.png">

even if I use `/apps/ocl-0.0.8-SNAPSHOT-jar-with-dependencies.jar` the loader tries to download the jar and not the pieces (see firefox network tab)

@alexp-sssup do I need anywhere a configuration file to tell the loader in how many files the .jar file is split up?

**Comment by vonwenckstern** [comment]
now github serves the jar file (maybe after scanning), and now the tool starts ;)

<img width="807" alt="bildschirmfoto 2017-12-02 um 22 13 58" src="https://user-images.githubusercontent.com/30497492/33519793-34ab6fc8-d7ae-11e7-88cc-9d0fc8f62ef7.png">

@ferdinandmehlan you need to store the content of the CDs in the file system so that the symbol table can load it correctly, that's why I guess we are getting the error. So that we can use it as before with the command-line

**Comment by vonwenckstern** [comment]
@ferdinandmehlan Just for your information:
@0xJMR creates soon an `iframe` version for the online-IDE, and then for the OCL-CD-Demosite he will replace the `textarea` boxes with the corresponding `iframe` ones so that you have Syntax-highlighting and Syntax error displaying when entering the text.
The aim is too present Prof. Rumpe at beginning of January a first version.

**Comment by vonwenckstern** [comment]
@ferdinandmehlan Thank you for your commit yesterday.

Did you use the new version @alexp-sssup used? (https://github.com/leaningtech/cheerpj-meta/issues/11#issuecomment-353728804)
If yes, can you please post a comment there, that there bug-fix did not help us, since I still get nullpointer exceptions. But the program is correct, did you change there anything, e.g. executing the method twice?

the console output I get at windows using Firefox:
```
Loading OCL Model!!
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
java.lang.NullPointerException
[WARN]  0xA1039 An artifact scope should have the global scope as enclosing scope or no enclosing scope at all.
[WARN]  0xA1039 An artifact scope should have the global scope as enclosing scope or no enclosing scope at all.
[WARN]  0xA1039 An artifact scope should have the global scope as enclosing scope or no enclosing scope at all.
[WARN]  0xA1039 An artifact scope should have the global scope as enclosing scope or no enclosing scope at all.
[WARN]  0xA1039 An artifact scope should have the global scope as enclosing scope or no enclosing scope at all.
[WARN]  0xA1042 Scope "Optional[size]" has already an enclosing scope.
[WARN]  0xA1039 An artifact scope should have the global scope as enclosing scope or no enclosing scope at all.
OCL Model loaded successfully!
```

By the way, can you enable the check button, when the OCL tool has finished again? Otherwise, we need to reload the page everytime.

PS: Do it whenever you have time ;) It is also ok, if it is next year -- since we all have Xmas break ;)

**Comment by vonwenckstern** [comment]
@ferdinandmehlan Thank you for yor commit today.
Now it works for me ;) And only due to your hard work.

This means we can use the OCL tool as demo for the Online IDE project which Jean-Marc will show Prof. Rumpe in 2nd week of January.

Thank you again.
Maybe in the first week of January you can fix the `enabling button issue` and comment out all console outputs (maybe you create a boolean flag, so that you can enable the outputs again).
And maybe we copy the instalbe JavaScript files to our github-pages (in case CheerpJ fixes another bug, which will cause other side effects -- just be sure that the tool works for the demo in January).

@ferdinandmehlan Thank you very much, and I wish you a Merry Xmas and a Happy New Year.
PS: In your seminar paper you can reference to this tool page, so that the other students reviewing your paper, can try different OCL listings there. (If you want to you can add a `div` box with some examples, when the student clicks at the button you set some code to OCL and to the CD. This would make it even easier for the reviewers to try out your code as they cannot produce type errors.
