### ISSUE TITLE
Fix OCL Grammar so that it is compatible to BR's book

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/OCL#5]
Right now we have some small differences between the OCL constraints in the MBSE book and our tooling:

* OCL constraints do not end with a semicolon
http://www.mbse.se-rwth.de/book1/index.php?c=chapter3-1#x1-400003.1.1
![grafik](https://user-images.githubusercontent.com/30497492/34379033-42c6b6e0-eaf9-11e7-9ba8-6c734d2e2caf.png)

![grafik](https://user-images.githubusercontent.com/30497492/34379048-5b5ac02a-eaf9-11e7-9716-a445783a1b9b.png)

![grafik](https://user-images.githubusercontent.com/30497492/34379066-76506b14-eaf9-11e7-83bf-2df20bb23be2.png)

* I am also wondering if we really need the `package` and the `ocl` keyword
    * classdiagrams have a `package` and a `classdiagramm` container keyword, since we are importing them again (e.g. in OCL), but do we reference from anywhere else to OCL constraints again (probably not); and if yes we still have the option to give the OCL constraint a name (after the `inv` keyword)
    * In my opinion we could just write down:
 ```
import classdiagramm1.Auction;
context Auction a inv test: 
  a.participants.size > 0;
```

@ferdinandmehlan What do you think? Did I miss any corner-case?

**Comment by ferdinandmehlan** [comment]
@vonwenckstern 
We don't import ocl yet, but sequence Diagramms do in theory and there was one project already looking into that. 

Also it is possible to have multiple constraints per file and with the ocl brackets around them one can load all with one name.


The semicolon is probably not needed.

**Comment by vonwenckstern** [comment]
@ferdinandmehlan Thank you for that information.

Ok, then we can make the `ocl FileName` optional, and if no file name is present then we just take a standard default file name.
Because for many cases (also for our non-functional ones describing the semantics), this spoils just up the code.
And I try to be as close as possible to Prof. Rumpe book: If anyone copies a constraint there, it should not have any parsing errors. (the import statement for the CD is just semantically needed to resolve the names; but I guess the reader will understand it).

**Comment by ferdinandmehlan** [comment]
I'll integrate this feature into the features-newgrammar branch, which should be done soon.

**Comment by ferdinandmehlan** [comment]
New Grammar integrated on new project, can be found here: https://github.com/MontiCore/OCL
